language: python
python:
  - "2.7"
  
install: "pip install SpeechRecognition gTTS mp3play beautifulsoup4 unicodedata2 dill ChatterBot"

before_script: echo @Preping the tests...

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python tests.py
