language: python
python:
  - "2.7"

branches:
  only:
    - master

install:
  - "pip install SpeechRecognition"
  - "pip install gTTS"
  - "pip install mp3play"
  - "pip install beautifulsoup4"
  - "pip install unicodedata2"
  - "pip install dill "
  - "pip install logging"
  - "pip install codecov"
  # - "pip install ChatterBot"

before_script:
  - echo Preping the tests...

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - coverage run -m unittests.test_launcher
  
after_success:
- codecov --token=f60e1429-5609-4466-b7a2-9294e0d25b79
